## enable or disable automatic update checks
update_check = false

## address of the sync server
# sync_address = "https://api.atuin.sh"

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
sync_frequency = "0"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "skim"

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = false

keymap_mode="vim-insert"

[sync]
records = true
